version: '3'
services:
  npx:
    container_name: sfeir-school-langchain
    image: node:20
    user: node
    command: npx serve
    volumes:
      - .:/sources
    working_dir: /sources
    ports:
      - 3000:3000
